export const Temp_Data = [
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "20%",
    Project_Due_Date: "28/10/20",
    Town_Name: "Thorala",
    Taluka_Name: "Rajkot East",
  },
  {
    Project_Name: "Garden New Plant",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "79%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Thorala",
    Taluka_Name: "Rajkot East",
  },
  {
    Project_Name: "School Development",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "62%",
    Project_Due_Date: "31/01/20",
    Town_Name: "Thorala",
    Taluka_Name: "Rajkot East",
  },
  {
    Project_Name: "School Painting",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Rajkot-1",
    Taluka_Name: "Rajkot East",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Rajkot-1",
    Taluka_Name: "Rajkot East",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Nana Mauva",
    Taluka_Name: "Rajkot West",
  },
  {
    Project_Name: "School Development",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Nana Mauva",
    Taluka_Name: "Rajkot West",
  },
  {
    Project_Name: "School Painting",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Nana Mauva",
    Taluka_Name: "Rajkot West",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Raiya",
    Taluka_Name: "Rajkot West",
  },
  {
    Project_Name: "Building Development",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Raiya",
    Taluka_Name: "Rajkot West",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "20%",
    Project_Due_Date: "28/10/20",
    Town_Name: "Jamnavad",
    Taluka_Name: "Dhoraji",
  },
  {
    Project_Name: "Garden New Plant",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "79%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Jamnavad",
    Taluka_Name: "Dhoraji",
  },
  {
    Project_Name: "School Painting",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Moti Marad",
    Taluka_Name: "Dhoraji",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Moti Marad",
    Taluka_Name: "Dhoraji",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Chikaliya",
    Taluka_Name: "Upleta",
  },
  {
    Project_Name: "School Development",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Chikaliya",
    Taluka_Name: "Upleta",
  },
  {
    Project_Name: "School Painting",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Chikaliya",
    Taluka_Name: "Upleta",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "20%",
    Project_Due_Date: "28/10/20",
    Town_Name: "Adhiya",
    Taluka_Name: "Jasdan",
  },
  {
    Project_Name: "Garden New Plant",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "79%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Adhiya",
    Taluka_Name: "Jasdan",
  },
  {
    Project_Name: "School Painting",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Ajmer",
    Taluka_Name: "Jasdan",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Ajmer",
    Taluka_Name: "Jasdan",
  },
  {
    Project_Name: "Road Construction",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Ambaradi",
    Taluka_Name: "Vinchhiya",
  },
  {
    Project_Name: "School Development",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Ambaradi",
    Taluka_Name: "Vinchhiya",
  },
  {
    Project_Name: "School Painting",
    Project_Status: null,
    Project_Status_Color: null,
    Project_Status_Value: "53%",
    Project_Due_Date: "30/05/20",
    Town_Name: "Ambaradi",
    Taluka_Name: "Vinchhiya",
  },
];
