import { StyleSheet } from "react-native";
import { scale } from "react-native-size-matters";
import { GlobalStyles } from "../../../constants/constColors";
import { normalizeText } from "../../../responsive-text";
export const styles = StyleSheet.create({
  main_container: {
    height: scale(80),
    width: "100%",
    borderBottomColor: GlobalStyles.colors.cardColor,
    borderBottomWidth: scale(1),
  },
  innerStyle: {
    flexDirection: "row",
    minHeight: "100%",
    minWidth: "80%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: scale(20),
  },
  profile_container: {
    height: scale(58),
    width: scale(58),
    borderRadius: scale(58),
    borderColor: "#ccc",
    borderWidth: scale(2),
    justifyContent: "center",
    alignContent: "center",
  },
  profile_TextStyle: {
    justifyContent: "flex-start",
    alignItems: "center",
    textAlign: "center",
    fontSize: normalizeText(24),
    fontWeight: "bold",
    color: GlobalStyles.colors.mainC,
  },
  title_style: {
    fontSize: normalizeText(16),
    fontWeight: "bold",
    color: "#1a1a1a",
    paddingLeft: scale(20),
  },
  lable_one_mainContainer: {
    paddingLeft: scale(20),
    flexDirection: "row",
    // alignSelf: "center",
    marginVertical: scale(5),
  },
  lable_one_innerContainer: {
    backgroundColor: "#FEF7E5",
    justifyContent: "center",
    borderRadius: scale(5),
    padding: scale(5),
    marginRight: scale(8),
    flexDirection: "row",
    alignItems: "center",
  },
  lable_one_TextStyle: {
    fontSize: normalizeText(10),
    color: "black",
    textAlign: "center",
    fontWeight: "bold",
  },
  lable_two_mainContainer: {
    justifyContent: "center",
    borderRadius: scale(5),
    padding: scale(5),
    marginRight: scale(8),
    flexDirection: "row",
    alignItems: "center",
  },
  lable_two_TextStyle: {
    fontSize: normalizeText(10),
    color: "black",
    textAlign: "center",
    fontWeight: "bold",
  },
  counter_mainContainer: {
    justifyContent: "flex-end",
    alignItems: "center",
    alignSelf: "center",
    height: scale(30),
    width: scale(30),
    borderRadius: scale(30),
    backgroundColor: "#00D02E",
    justifyContent: "center",
  },
  counter_TextStyle: {
    color: "white",
    alignSelf: "center",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: normalizeText(12),
  },
});
